---
apiVersion: v1
kind: Service
metadata:
  name: kafka-bootstrap
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
  clusterIP: None
  selector:
    app: kafka
